### ISSUE TITLE
create wireframes/sketches

### ISSUE THREAD

**Issue by Oldman10000** [liamthetate/hackathon#2]

**Comment by IainKnox** [comment]
👍🏻

**Comment by dandavies23** [comment]
There's some great LR album covers here and the hair could possibly be part of the biscuit: https://www.dropbox.com/sh/vrpktidbyi8v9q7/AAD4CNH6ewkWN7KcXoFL2txBa?dl=0

**Comment by dandavies23** [comment]
![lionel-richie-all-night-long](https://user-images.githubusercontent.com/566086/128333022-8b3916bf-c15b-429b-8c52-1ec7ae616886.jpeg)
![LionelRichie-DOTC](https://user-images.githubusercontent.com/566086/128333036-d7af3bdb-6894-4f56-987b-c30e7e673d10.jpeg)
![LionelRichie-YouAre](https://user-images.githubusercontent.com/566086/128333040-92eb061a-310d-4d4c-b0a4-016f3eb40ec2.jpg)
![LionelRichie](https://user-images.githubusercontent.com/566086/128333044-aa37c3d8-603b-4555-992f-e138837eea5c.jpeg)

**Comment by IainKnox** [comment]
Yeah, i think a massive afro should be the focal point

**Comment by IainKnox** [comment]
![5685005215_7000ee0c12_o](https://user-images.githubusercontent.com/88481059/128573520-46273cc6-517e-4a96-8db5-d77de3ad798f.jpg)

**Comment by IainKnox** [comment]
![Musician Pixel Figures](https://user-images.githubusercontent.com/88481059/128573889-7db64041-3c88-410a-a04b-f9ad71d5a65e.jpg)

Some pixelart figures...including a MJ

**Comment by IainKnox** [comment]
Ive created a low fidelity wireframe, so how/where do I upload it for you all to have a look through?

**Comment by IainKnox** [comment]
[Wireframe.zip](https://github.com/liamthetate/hackathon/files/6948733/Wireframe.zip)

**Comment by IainKnox** [comment]
didnt realize I could zip it as a .PNG <noob>
